---
- name: Use collection to watch Tower itself
  hosts: all
  tasks:
  - name: List all insights succeded jobs
    ansible.tower.tower_job_list:
      status: successful
      query: {"playbook": "insights.yml"}
      tower_host: 192.168.122.221
      tower_username: admin
      tower_password: redhat
      validate_certs: no
    register: jobs
    
  - name: Print
    debug:
      msg: "{{ jobs.results_lines}}"
